---
- name: Install openldap packages
  become: true
  ansible.builtin.apt:
    name:
      - slapd
      - ldap-utils
      - python3-ldap
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Start ldap service
  become: true
  ansible.builtin.service:
    name: slapd
    state: started
    enabled: true

- name: Register encripted password
  ansible.builtin.command: slappasswd -s "{{ openldap_bind_password }}"
  register: openldap_encripted_password

- name: Copy Grafana Configuration
  become: true
  ansible.builtin.copy:
    content: |
      dn: olcDatabase={{ openldap_db_type }},cn=config
      changetype: modify
      replace: olcSuffix
      olcSuffix: {{ openldap_base_dn }}

      dn: olcDatabase={{ openldap_db_type }},cn=config
      changetype: modify
      replace: olcRootDN
      olcRootDN: {{ openldap_base_dn }}

      dn: olcDatabase={{ openldap_db_type }},cn=config
      changetype: modify
      replace: olcRootPW
      olcRootPW: {{ openldap_encripted_password.stdout }}
    dest: /tmp/db.ldif
    owner: root
    group: root
    mode: "0664"

- name: Load ddbb template into ldap
  become: true
  ansible.builtin.command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/db.ldif

- name: Ensure LDPA service is running
  become: true
  ansible.builtin.systemd:
    name: slapd
    state: started
    enabled: true

- name: Wait for keycloak to be up
  ansible.builtin.uri:
    url: http://localhost:{{ keycloak_port }}/auth/admin/master/console/
    follow_redirects: none
    method: GET
  register: _result
  until: _result.status == 200
  retries: 30
  delay: 5
  changed_when: false

- name: Load ldap root entry
  community.general.ldap_entry:
    server_uri: "{{ openldap_server_uri }}"
    bind_dn: "{{ openldap_base_dn }}"
    bind_pw: "{{ openldap_bind_password }}"
    dn: "{{ openldap_base_dn }}"
    objectClass:
      - top
      - domain
